# Generated by Django 2.1.7 on 2019-02-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_date', models.DateTimeField(null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(related_name='orders', to='books.Book')),
            ],
        ),
    ]
